
const defaultLang = "de";
const supportedLangs = ["de", "en", "tr"];
const localeMap = { de: "de_DE", en: "en_GB", tr: "tr_TR" };

const translations = {
  de: {
    common: {
      htmlLang: "de",
      skipLink: "Zum Inhalt springen",
      brandAria: "Sultan Startseite",
      navAria: "Hauptnavigation",
      switcherAria: "Sprache wählen",
      brandTagline: "Wo Qualität Geschmack bekommt",
      nav: { home: "Start", store: "Unser Laden", story: "Geschichte", menu: "Speisekarte", drinks: "Getränke", contact: "Kontakt", imprint: "Impressum", privacy: "Datenschutz" },
      halalTitle: "100% Halal",
      halalText: "Alle Gerichte bei Sultan werden ausschließlich mit Halal-zertifizierten Zutaten zubereitet.",
      footerCopy: "© 2026 Sultan Gemüse Kebab – Wo Qualität Geschmack bekommt"
    },
    pages: {
      home: {
        title: "Sultan Gemüse Kebab Berlin – Wo Qualität Geschmack bekommt",
        description: "Sultan Gemüse Kebab in Berlin Lichterfelde. 25 Jahre Erfahrung, 24 Stunden gereifter Teig für Pizza und Brot, frische Zubereitung und ehrlicher Geschmack.",
        heroEyebrow: "Sultan Gemüse Kebab · Berlin-Lichterfelde",
        heroTitle: "Sultan Gemüse Kebab.<br>Frisch belegt.<br>Heiß serviert.",
        heroLead: "25 Jahre Erfahrung, täglich frische Zubereitung und 24 Stunden gereifter Teig für Pizza und Brot. Bei Sultan geht es um ehrlichen Geschmack, klare Qualität und Gerichte, auf die man direkt Appetit bekommt.",
        ctas: ["Speisekarte ansehen", "Route öffnen"],
        highlights: [["25 Jahre", "Erfahrung in Würze, Timing und sauberer Zubereitung."], ["24 Stunden", "gereifter Teig für Pizza und Brot."], ["Täglich", "frische Falafel, frisches Gemüse und klare Handschrift."]],
        minis: [["Chicken Gemüse Kebab", "Saftiges Chicken, frische Füllung und Saucen, die den Geschmack tragen."], ["Falafel, Lahmacun, Pizza", "Klar aufgebaut, warm serviert und direkt auf den Punkt."], ["Wo Qualität Geschmack bekommt", "Frische, Sorgfalt und ehrliche Produkte statt leere Versprechen."]],
        section1: ["Was Sultan ausmacht", "Ehrliche Qualität. Klare Karte. Starker Geschmack.", "Knackiges Gemüse, warme Brote, gereifter Teig und saubere Abläufe machen den Unterschied. Alles bleibt bewusst klar, damit jedes Produkt seinen Platz hat."],
        cards: [["Frische Zutaten", "Saftiges Chicken, täglich frische Falafel und Gemüse, das Biss und Frische bringt."], ["Eigene Handschrift", "Sultan arbeitet ruhig, sauber und mit Geschmack, der nicht laut sein muss."], ["Ein Besuch, der sich lohnt", "Warm, würzig und direkt – für den schnellen Hunger genauso wie für den bewussten Stopp."]],
        visualCaption: "Klar im Auftritt. Stark im Geschmack. Ehrlich in der Küche.",
        section2: ["Mehr von Sultan", "Alles Wichtige schnell gefunden.", "Vom Laden über die Geschichte bis zur Speisekarte bleibt alles klar, direkt und ohne Umwege aufgebaut."],
        pageLinks: [["Unser Laden", "Atmosphäre, Ordnung und die Haltung hinter Sultan."], ["Geschichte", "25 Jahre Erfahrung und der Weg zu einem eigenen Ort."], ["Speisekarte", "Döner, Falafel, Lahmacun, Pizza, Salate und Desserts."], ["Getränke", "Elephant Bay, Ayran und stilles Wasser – passend zum Essen."]],
        contact: ["Standort", "Sultan ist in Berlin-Lichterfelde schnell gefunden.", "Sultan Gemüse Kebab<br>Ostpreußendamm 79<br>12207 Berlin", "Montag – Sonntag<br>11:00 – 00:00 Uhr", "In Google Maps öffnen", "Sultan auf Google Maps"]
      },
      store: {
        title: "Unser Laden – Sultan Gemüse Kebab Berlin",
        description: "Sultan in Berlin Lichterfelde: frische Küche, ehrliche Qualität und ein Laden mit eigener Handschrift.",
        eyebrow: "Unser Laden", heroTitle: "Ein Ort, der sauber arbeitet und warm empfängt.", heroLead: "Sultan verbindet frische Küche mit klarer Ordnung, ehrlicher Qualität und einer Atmosphäre, in der man gerne kurz innehält. Alles soll direkt, verlässlich und appetitlich wirken.",
        pills: ["Frisch", "Sauber", "Herzlich", "Verlässlich"], caption: "Sultan bleibt ruhig im Auftritt und klar im Geschmack.",
        cards: [["Saubere Vorbereitung", "Frische Zutaten, geordnete Abläufe und ein Anspruch, der nicht erst am Tresen beginnt."], ["Qualität im Alltag", "25 Jahre Erfahrung zeigen sich dort, wo Würze, Temperatur und Timing stimmen."], ["Eigene Handschrift", "Warm, klar und wiedererkennbar – nicht laut, sondern überzeugend durch Sorgfalt."]]
      },
      story: {
        title: "Geschichte – Sultan Gemüse Kebab Berlin",
        description: "Die Geschichte von Sultan Gemüse Kebab: 25 Jahre Erfahrung, Familie und der Wunsch nach einem eigenen Ort mit Handschrift.",
        eyebrow: "Geschichte", heroTitle: "Aus Erfahrung gewachsen. Für echten Geschmack gemacht.", heroLead: "Sultan ist aus vielen Jahren Arbeit, familiärer Prägung und dem Wunsch entstanden, einen eigenen Ort mit klarer Handschrift aufzubauen. Was heute ruhig wirkt, ist über lange Zeit gereift.",
        pills: ["25 Jahre Erfahrung", "Familienbetrieb", "24h gereifter Teig"], caption: "Wo Qualität Geschmack bekommt – nicht als Spruch, sondern als täglicher Maßstab.",
        cards: [["Erfahrung", "Routine zeigt sich dort, wo Würze, Temperatur und Timing nicht dem Zufall überlassen werden."], ["Familie", "Sultan trägt die Nähe, Verlässlichkeit und Verantwortung eines Familienbetriebs in den Alltag."], ["Handschrift", "Ein eigener Ort entsteht erst dann, wenn Geschmack, Haltung und Wiedererkennbarkeit zusammenpassen."]]
      },
      drinks: {
        title: "Getränke – Sultan Gemüse Kebab Berlin",
        description: "Getränke bei Sultan: Elephant Bay, stilles Wasser und Ayran – gut gekühlt, klar im Geschmack und passend zu Kebabs, Lahmacun und Pizza.",
        eyebrow: "Getränke", heroTitle: "Kühl, klar und genau richtig zum Essen.", heroLead: "Würzige Gerichte brauchen eine frische Begleitung. Deshalb bleibt die Auswahl bei Sultan bewusst klar: Elephant Bay, stilles Wasser und Ayran – gut gekühlt und direkt passend.",
        ctas: ["Speisekarte", "Kontakt"], minis: [["Passend zum Essen", "Frisch, leicht und so gewählt, dass der Geschmack der Gerichte im Mittelpunkt bleibt."], ["Bewusst klar", "Lieber passend als überladen – genau wie bei der Karte."]],
        blockTitle: "Erfrischungen", blockLead: "Ob zum Kebab, zur Pizza oder einfach für zwischendurch: Ein kalter Schluck rundet das Ganze ab, ohne den Geschmack zu verdecken.",
        items: [["Elephant Bay", "330 ml"], ["Stilles Wasser", "500 ml"], ["Ayran", "250 ml · Allergen 7"]], note: "Gut gekühlt, klar im Geschmack und passend zu würzigen Gerichten."
      },
      contact: {
        title: "Kontakt – Sultan Gemüse Kebab Berlin",
        description: "Kontakt, Adresse, Telefonnummer, Öffnungszeiten und direkter Weg zu Sultan Gemüse Kebab in Berlin Lichterfelde.",
        eyebrow: "Kontakt", heroTitle: "Sultan ist schnell gefunden und direkt erreichbar.", heroLead: "Adresse, Öffnungszeiten, Telefonnummer und die direkte Route zu Sultan auf einen Blick. Kurz, klar und ohne Umwege.",
        cta2: "Route öffnen", minis: [["Adresse", "Ostpreußendamm 79<br>12207 Berlin-Lichterfelde"], ["Öffnungszeiten", "Montag – Sonntag<br>11:00 – 00:00 Uhr"], ["E-Mail", '<a href="mailto:dnmz.unternehmen@outlook.de">dnmz.unternehmen@outlook.de</a>']],
        infoTitle: "Direkter Kontakt", infoParas: ["Sultan Gemüse Kebab<br>Ostpreußendamm 79<br>12207 Berlin", 'Telefon<br><a href="tel:+4917632518597">0176 32518597</a>', 'E-Mail<br><a href="mailto:dnmz.unternehmen@outlook.de">dnmz.unternehmen@outlook.de</a>'], mapsOpen: "In Google Maps öffnen", mapTitle: "Sultan auf Google Maps"
      },
      imprint: {
        title: "Impressum – Sultan Gemüse Kebab Berlin", description: "Impressum von Sultan Gemüse Kebab in Berlin mit allen gesetzlich erforderlichen Angaben.", eyebrow: "Impressum", heroTitle: "Rechtlich klar und direkt erreichbar.", heroLead: "Alle gesetzlich erforderlichen Angaben zu Sultan Gemüse Kebab auf einen Blick.",
        paras: ["Angaben gemäß § 5 DDG", "Sultan Gemüse Kebab<br>Einzelunternehmen<br>Ostpreußendamm 79<br>12207 Berlin<br>Deutschland", "Vertreten durch:<br>Hulusi Dönmez", 'Kontakt:<br>E-Mail: <a href="mailto:dnmz.unternehmen@outlook.de">dnmz.unternehmen@outlook.de</a><br>Telefon: <a href="tel:+4917632518597">0176 32518597</a>', "Umsatzsteuer-Identifikationsnummer gemäß § 27a Umsatzsteuergesetz:<br>DE2026300369"]
      },
      privacy: {
        title: "Datenschutz – Sultan Gemüse Kebab Berlin", description: "Datenschutzhinweise von Sultan Gemüse Kebab für diese Website, eingebettete Karten und Kontaktaufnahme per E-Mail.", eyebrow: "Datenschutz", heroTitle: "Datenschutz verständlich zusammengefasst.", heroLead: "Informationen zur Verarbeitung personenbezogener Daten auf dieser Website, bei der Kartenanzeige und bei Kontaktaufnahme per E-Mail.",
        paras: ["Der Schutz Ihrer personenbezogenen Daten ist uns wichtig. Diese Website informiert über Sultan Gemüse Kebab und unser gastronomisches Angebot.", "Beim Aufruf der Website können technisch erforderliche Daten verarbeitet werden. Dazu gehören insbesondere IP-Adresse, Datum und Uhrzeit des Zugriffs, Browsertyp, Betriebssystem und die aufgerufenen Seiten.", "Diese Website wird über GitHub Pages bereitgestellt. Anbieter ist GitHub, Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, USA.", "Auf der Startseite und der Kontaktseite sind Google-Maps-Karten eingebettet. Beim Laden dieser Karten können Daten, insbesondere Ihre IP-Adresse, an Google übermittelt werden. Anbieter ist Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland.", "Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir die von Ihnen übermittelten Angaben ausschließlich zur Bearbeitung Ihrer Anfrage.", 'Verantwortlich für die Datenverarbeitung:<br>Hulusi Dönmez<br>Sultan Gemüse Kebab<br>Ostpreußendamm 79<br>12207 Berlin<br>E-Mail: <a href="mailto:dnmz.unternehmen@outlook.de">dnmz.unternehmen@outlook.de</a><br>Telefon: <a href="tel:+4917632518597">0176 32518597</a>']
      },
      menu: {
        title: "Speisekarte – Sultan Gemüse Kebab Berlin", description: "Die Speisekarte von Sultan mit Chicken Gemüse Kebab, Falafel, Lahmacun, Pizza, Salaten, Sides, Desserts und 24 Stunden gereiftem Teig für Pizza und Brot.",
        eyebrow: "Speisekarte", heroTitle: "Alles, worauf man direkt Appetit bekommt.", heroLead: "Chicken Gemüse Kebab, Falafel, Lahmacun, Pizza, Salate und Desserts – klar gegliedert, schnell lesbar und mit Geschmack, der frisch und voll bleibt.",
        ctas: ["Getränke", "Jetzt vorbeikommen"], mini: ["24 Stunden gereifter Teig", "Für Pizza und Brot bekommt der Teig bei Sultan die Ruhe, die man später schmeckt."],
        block1Title: "Döner", block1Subheads: ["Falafel", "Extras"], block1Items: [["Bowl", "Chicken Gemüse Kebab · Allergene 1,6,7"], ["Dürüm", "Chicken Gemüse Kebab · Allergene 1,6,7"], ["Box", "Chicken Gemüse Kebab · Allergene 1,6,7"], ["Brot", "Chicken Gemüse Kebab · Allergene 1,6,7"], ["Bowl", "Falafel Gemüse Kebab · Allergene 1,6,11"], ["Dürüm", "Falafel Gemüse Kebab · Allergene 1,6,11"], ["Box", "Falafel Gemüse Kebab · Allergene 1,6,11"], ["Brot", "Falafel Gemüse Kebab · Allergene 1,6,11"], ["Chicken extra", "Allergene 6,7"], ["Falafel extra", "Allergene 1,11"], ["Brot extra", "Allergen 1"]],
        sauces: "Saucen: Kräuter · Knoblauch · Scharf Vegan · Knoblauch Vegan · Sesam Vegan.",
        block2Title: "Lahmacun", block2Subhead: "Pizza 28 cm", block2Items: [["10 Stück", "frisch aus dem Ofen · Allergen 1"], ["5 Stück", "frisch aus dem Ofen · Allergen 1"], ["3 Stück", "frisch aus dem Ofen · Allergen 1"], ["1 Stück", "frisch aus dem Ofen · Allergen 1"], ["Tonno", "Tomatensauce & Mozzarella · Thunfisch, Zwiebeln"], ["Sucuk", "Tomatensauce & Mozzarella"], ["Salami", "Tomatensauce & Mozzarella"], ["Prosciutto", "Tomatensauce & Mozzarella · Putenbrust"], ["Mista", "Tomatensauce & Mozzarella · Putenbrust, Salami"], ["Funghi", "Tomatensauce & Mozzarella · Champignons"], ["Vegetaria", "Tomatensauce & Mozzarella · Zucchini, Aubergine, Paprika"], ["Mozzarella", "extra Mozzarella"], ["Margherita", "Mozzarella"]],
        block3Title: "Salate & Sides", block3Items: [["Salat Thunfisch", "frisch und leicht"], ["Salat Käse", "frisch und leicht"], ["Salat Gemischt", "frisch und leicht"], ["Linsensuppe", "wärmend und klassisch"], ["Pommes", "knusprig serviert"], ["Falafel 4 Stück", "Allergene 1,11"]],
        block4Title: "Dessert", block4Items: [["Baklava 3 Stück", "Allergene 1,3,7,8"], ["Burma 3 Stück", "Allergene 1,3,7,8"]], dessertNote: "Allergene auf Anfrage. Bei Fragen zu Zutaten und Allergenen helfen wir direkt vor Ort weiter."
      }
    }
  },
  en: {
    common: {
      htmlLang: "en", skipLink: "Skip to content", brandAria: "Sultan homepage", navAria: "Main navigation", switcherAria: "Choose language", brandTagline: "Where quality meets flavor",
      nav: { home: "Home", store: "Our Place", story: "Story", menu: "Menu", drinks: "Drinks", contact: "Contact", imprint: "Legal Notice", privacy: "Privacy" },
      halalTitle: "100% Halal", halalText: "All dishes at Sultan are prepared exclusively with halal-certified ingredients.", footerCopy: "© 2026 Sultan Gemüse Kebab – Where quality meets flavor"
    },
    pages: {
      home: { title: "Sultan Gemüse Kebab Berlin – Where quality meets flavor", description: "Sultan Gemüse Kebab in Berlin Lichterfelde. 25 years of experience, 24-hour matured dough for pizza and bread, fresh preparation and honest flavor.", heroEyebrow: "Sultan Gemüse Kebab · Berlin-Lichterfelde", heroTitle: "Sultan Gemüse Kebab.<br>Freshly filled.<br>Served hot.", heroLead: "25 years of experience, freshly prepared every day and 24-hour matured dough for pizza and bread. At Sultan, everything is about honest flavor, clear quality and dishes that instantly make you hungry.", ctas: ["View menu", "Open route"], highlights: [["25 years", "of experience in seasoning, timing and clean preparation."], ["24 hours", "matured dough for pizza and bread."], ["Daily", "fresh falafel, fresh vegetables and a clear signature."]], minis: [["Chicken vegetable kebab", "Juicy chicken, fresh fillings and sauces that carry the flavor."], ["Falafel, lahmacun, pizza", "Clearly structured, served hot and exactly on point."], ["Where quality meets flavor", "Freshness, care and honest products instead of empty promises."]], section1: ["What defines Sultan", "Honest quality. Clear menu. Strong flavor.", "Crunchy vegetables, warm bread, matured dough and clean processes make the difference. Everything stays intentionally clear so every product has its place."], cards: [["Fresh ingredients", "Juicy chicken, daily fresh falafel and vegetables that bring bite and freshness."], ["Own signature", "Sultan works calmly, cleanly and with flavor that does not need to be loud."], ["A visit worth making", "Warm, spicy and direct – for a quick bite as well as a deliberate stop."]], visualCaption: "Clear in appearance. Strong in flavor. Honest in the kitchen.", section2: ["More from Sultan", "Everything important at a glance.", "From the place itself to the story and the menu, everything stays clear, direct and without detours."], pageLinks: [["Our Place", "Atmosphere, order and the attitude behind Sultan."], ["Story", "25 years of experience and the path toward a place of our own."], ["Menu", "Kebab, falafel, lahmacun, pizza, salads and desserts."], ["Drinks", "Elephant Bay, ayran and still water – the right match for the food."]], contact: ["Location", "Sultan is easy to find in Berlin-Lichterfelde.", "Sultan Gemüse Kebab<br>Ostpreußendamm 79<br>12207 Berlin", "Monday – Sunday<br>11:00 AM – 12:00 AM", "Open in Google Maps", "Sultan on Google Maps"] },
      store: { title: "Our Place – Sultan Gemüse Kebab Berlin", description: "Sultan in Berlin Lichterfelde: fresh food, honest quality and a place with its own signature.", eyebrow: "Our Place", heroTitle: "A place that works cleanly and welcomes warmly.", heroLead: "Sultan combines fresh food with clear order, honest quality and an atmosphere where people like to pause for a moment. Everything should feel direct, reliable and appetizing.", pills: ["Fresh", "Clean", "Warm", "Reliable"], caption: "Sultan stays calm in appearance and clear in flavor.", cards: [["Clean preparation", "Fresh ingredients, organized processes and a standard that starts long before the counter."], ["Everyday quality", "25 years of experience show where seasoning, temperature and timing are right."], ["Own signature", "Warm, clear and recognizable – not loud, but convincing through care."]] },
      story: { title: "Story – Sultan Gemüse Kebab Berlin", description: "The story of Sultan Gemüse Kebab: 25 years of experience, family and the desire for a place with its own signature.", eyebrow: "Story", heroTitle: "Grown from experience. Made for real flavor.", heroLead: "Sultan grew out of many years of work, family roots and the desire to build a place with a clear signature. What appears calm today has matured over a long time.", pills: ["25 years of experience", "Family business", "24h matured dough"], caption: "Where quality meets flavor – not just a slogan, but a daily standard.", cards: [["Experience", "Routine shows where seasoning, temperature and timing are never left to chance."], ["Family", "Sultan brings the closeness, reliability and responsibility of a family business into everyday life."], ["Signature", "A place only becomes its own when flavor, attitude and recognizability fit together."]] },
      drinks: { title: "Drinks – Sultan Gemüse Kebab Berlin", description: "Drinks at Sultan: Elephant Bay, still water and ayran – chilled, clear in taste and perfect with kebabs, lahmacun and pizza.", eyebrow: "Drinks", heroTitle: "Cool, clear and just right with food.", heroLead: "Spicy dishes need a fresh companion. That is why Sultan keeps the selection intentionally clear: Elephant Bay, still water and ayran – well chilled and perfectly matched.", ctas: ["Menu", "Contact"], minis: [["Perfect with food", "Fresh, light and chosen so the dishes remain the center of attention."], ["Intentionally clear", "Better fitting than overloaded – just like the menu."]], blockTitle: "Refreshments", blockLead: "Whether with kebab, pizza or simply in between: a cold sip completes the experience without covering the flavor.", items: [["Elephant Bay", "330 ml"], ["Still water", "500 ml"], ["Ayran", "250 ml · Allergen 7"]], note: "Well chilled, clear in taste and a perfect match for spicy dishes." },
      contact: { title: "Contact – Sultan Gemüse Kebab Berlin", description: "Contact, address, phone number, opening hours and direct route to Sultan Gemüse Kebab in Berlin Lichterfelde.", eyebrow: "Contact", heroTitle: "Sultan is easy to find and directly reachable.", heroLead: "Address, opening hours, phone number and the direct route to Sultan at a glance. Short, clear and without detours.", cta2: "Open route", minis: [["Address", "Ostpreußendamm 79<br>12207 Berlin-Lichterfelde"], ["Opening hours", "Monday – Sunday<br>11:00 AM – 12:00 AM"], ["E-mail", '<a href="mailto:dnmz.unternehmen@outlook.de">dnmz.unternehmen@outlook.de</a>']], infoTitle: "Direct contact", infoParas: ["Sultan Gemüse Kebab<br>Ostpreußendamm 79<br>12207 Berlin", 'Phone<br><a href="tel:+4917632518597">0176 32518597</a>', 'E-mail<br><a href="mailto:dnmz.unternehmen@outlook.de">dnmz.unternehmen@outlook.de</a>'], mapsOpen: "Open in Google Maps", mapTitle: "Sultan on Google Maps" },
      imprint: { title: "Legal Notice – Sultan Gemüse Kebab Berlin", description: "Legal notice of Sultan Gemüse Kebab in Berlin with all legally required information.", eyebrow: "Legal Notice", heroTitle: "Legally clear and directly reachable.", heroLead: "All legally required information about Sultan Gemüse Kebab at a glance.", paras: ["Information according to § 5 DDG", "Sultan Gemüse Kebab<br>Sole proprietorship<br>Ostpreußendamm 79<br>12207 Berlin<br>Germany", "Represented by:<br>Hulusi Dönmez", 'Contact:<br>E-mail: <a href="mailto:dnmz.unternehmen@outlook.de">dnmz.unternehmen@outlook.de</a><br>Phone: <a href="tel:+4917632518597">0176 32518597</a>', "VAT identification number according to § 27a German VAT Act:<br>DE2026300369"] },
      privacy: { title: "Privacy – Sultan Gemüse Kebab Berlin", description: "Privacy information from Sultan Gemüse Kebab for this website, embedded maps and contact via email.", eyebrow: "Privacy", heroTitle: "Privacy clearly summarized.", heroLead: "Information about the processing of personal data on this website, when displaying maps and when contacting us by e-mail.", paras: ["The protection of your personal data is important to us. This website provides information about Sultan Gemüse Kebab and our gastronomic offer.", "When you access the website, technically necessary data may be processed. This includes in particular IP address, date and time of access, browser type, operating system and the pages accessed.", "This website is provided via GitHub Pages. The provider is GitHub, Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, USA.", "Google Maps is embedded on the home page and contact page. When these maps are loaded, data, especially your IP address, may be transmitted to Google. The provider is Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland.", "If you contact us by e-mail, we process the information you provide exclusively for handling your inquiry.", 'Responsible for data processing:<br>Hulusi Dönmez<br>Sultan Gemüse Kebab<br>Ostpreußendamm 79<br>12207 Berlin<br>E-mail: <a href="mailto:dnmz.unternehmen@outlook.de">dnmz.unternehmen@outlook.de</a><br>Phone: <a href="tel:+4917632518597">0176 32518597</a>'] },
      menu: { title: "Menu – Sultan Gemüse Kebab Berlin", description: "Sultan’s menu with chicken vegetable kebab, falafel, lahmacun, pizza, salads, sides, desserts and 24-hour matured dough for pizza and bread.", eyebrow: "Menu", heroTitle: "Everything that makes you hungry right away.", heroLead: "Chicken vegetable kebab, falafel, lahmacun, pizza, salads and desserts – clearly structured, easy to read and full of fresh flavor.", ctas: ["Drinks", "Visit now"], mini: ["24-hour matured dough", "For pizza and bread, Sultan gives the dough the rest you can taste later."], block1Title: "Kebab", block1Subheads: ["Falafel", "Extras"], block1Items: [["Bowl", "Chicken vegetable kebab · Allergens 1,6,7"], ["Dürüm", "Chicken vegetable kebab · Allergens 1,6,7"], ["Box", "Chicken vegetable kebab · Allergens 1,6,7"], ["Bread", "Chicken vegetable kebab · Allergens 1,6,7"], ["Bowl", "Falafel vegetable kebab · Allergens 1,6,11"], ["Dürüm", "Falafel vegetable kebab · Allergens 1,6,11"], ["Box", "Falafel vegetable kebab · Allergens 1,6,11"], ["Bread", "Falafel vegetable kebab · Allergens 1,6,11"], ["Extra chicken", "Allergens 6,7"], ["Extra falafel", "Allergens 1,11"], ["Extra bread", "Allergen 1"]], sauces: "Sauces: Herbs · Garlic · Spicy Vegan · Garlic Vegan · Sesame Vegan.", block2Title: "Lahmacun", block2Subhead: "Pizza 28 cm", block2Items: [["10 pieces", "fresh from the oven · Allergen 1"], ["5 pieces", "fresh from the oven · Allergen 1"], ["3 pieces", "fresh from the oven · Allergen 1"], ["1 piece", "fresh from the oven · Allergen 1"], ["Tonno", "Tomato sauce & mozzarella · tuna, onions"], ["Sucuk", "Tomato sauce & mozzarella"], ["Salami", "Tomato sauce & mozzarella"], ["Prosciutto", "Tomato sauce & mozzarella · turkey breast"], ["Mista", "Tomato sauce & mozzarella · turkey breast, salami"], ["Funghi", "Tomato sauce & mozzarella · mushrooms"], ["Vegetaria", "Tomato sauce & mozzarella · zucchini, aubergine, bell pepper"], ["Mozzarella", "extra mozzarella"], ["Margherita", "mozzarella"]], block3Title: "Salads & Sides", block3Items: [["Tuna salad", "fresh and light"], ["Cheese salad", "fresh and light"], ["Mixed salad", "fresh and light"], ["Lentil soup", "warming and classic"], ["Fries", "served crispy"], ["Falafel 4 pieces", "Allergens 1,11"]], block4Title: "Dessert", block4Items: [["Baklava 3 pieces", "Allergens 1,3,7,8"], ["Burma 3 pieces", "Allergens 1,3,7,8"]], dessertNote: "Allergens available on request. If you have questions about ingredients and allergens, we will gladly help you on site." }
    }
  },
  tr: {
    common: { htmlLang: "tr", skipLink: "İçeriğe geç", brandAria: "Sultan ana sayfa", navAria: "Ana navigasyon", switcherAria: "Dil seçimi", brandTagline: "Kalitenin lezzetle buluştuğu yer", nav: { home: "Ana Sayfa", store: "Mekanımız", story: "Hikaye", menu: "Menü", drinks: "İçecekler", contact: "İletişim", imprint: "Künye", privacy: "Gizlilik" }, halalTitle: "%100 Helal", halalText: "Sultan'da sunulan tüm yemekler yalnızca helal sertifikalı ürünlerle hazırlanır.", footerCopy: "© 2026 Sultan Gemüse Kebab – Kalitenin lezzetle buluştuğu yer" },
    pages: {
      home: { title: "Sultan Gemüse Kebab Berlin – Kalitenin lezzetle buluştuğu yer", description: "Berlin Lichterfelde’de Sultan Gemüse Kebab. 25 yıllık deneyim, pizza ve ekmek için 24 saat dinlendirilmiş hamur, taze hazırlık ve dürüst lezzet.", heroEyebrow: "Sultan Gemüse Kebab · Berlin-Lichterfelde", heroTitle: "Sultan Gemüse Kebab.<br>Taze hazırlanır.<br>Sıcak servis edilir.", heroLead: "25 yıllık deneyim, her gün taze hazırlık ve pizza ile ekmek için 24 saat dinlendirilmiş hamur. Sultan’da her şey dürüst lezzet, net kalite ve iştah açan yemekler etrafında şekillenir.", ctas: ["Menüyü görüntüle", "Yol tarifi aç"], highlights: [["25 yıl", "baharat, zamanlama ve temiz hazırlık deneyimi."], ["24 saat", "pizza ve ekmek için dinlendirilmiş hamur."], ["Her gün", "taze falafel, taze sebze ve belirgin bir imza."]], minis: [["Tavuklu sebzeli kebap", "Sulu tavuk, taze iç malzeme ve tadı taşıyan soslar."], ["Falafel, lahmacun, pizza", "Net hazırlanır, sıcak servis edilir ve tam kararında sunulur."], ["Kalitenin lezzetle buluştuğu yer", "Boş vaatler yerine tazelik, özen ve dürüst ürünler."]], section1: ["Sultan’ı özel yapan", "Dürüst kalite. Net menü. Güçlü lezzet.", "Çıtır sebzeler, sıcak ekmekler, dinlendirilmiş hamur ve temiz süreçler fark yaratır. Her ürünün yeri belli olsun diye her şey bilinçli şekilde sade tutulur."], cards: [["Taze malzemeler", "Sulu tavuk, her gün taze falafel ve diri kalan taze sebzeler."], ["Kendine özgü çizgi", "Sultan sakin, temiz ve gösterişsiz ama güçlü bir lezzet anlayışıyla çalışır."], ["Uğramaya değer", "Sıcak, baharatlı ve doğrudan – hızlı bir öğün için de bilinçli bir mola için de ideal."]], visualCaption: "Görünüşte net. Lezzette güçlü. Mutfakta dürüst.", section2: ["Sultan’dan daha fazlası", "Gerekli her şey hızlıca elinizin altında.", "Mekândan hikayeye ve menüye kadar her şey net, doğrudan ve dolambaçsız şekilde sunulur."], pageLinks: [["Mekanımız", "Atmosfer, düzen ve Sultan’ın arkasındaki duruş."], ["Hikaye", "25 yıllık deneyim ve kendi yerine giden yol."], ["Menü", "Döner, falafel, lahmacun, pizza, salatalar ve tatlılar."], ["İçecekler", "Elephant Bay, ayran ve su – yemeklere tam uyum sağlar."]], contact: ["Konum", "Sultan, Berlin-Lichterfelde’de kolayca bulunur.", "Sultan Gemüse Kebab<br>Ostpreußendamm 79<br>12207 Berlin", "Pazartesi – Pazar<br>11:00 – 00:00", "Google Maps’te aç", "Google Maps’te Sultan"] },
      store: { title: "Mekanımız – Sultan Gemüse Kebab Berlin", description: "Berlin Lichterfelde’de Sultan: taze mutfak, dürüst kalite ve kendine özgü bir mekân.", eyebrow: "Mekanımız", heroTitle: "Temiz çalışan ve sıcak karşılayan bir yer.", heroLead: "Sultan; taze mutfağı, düzenli çalışma anlayışını, dürüst kaliteyi ve kısa bir mola vermek isteyeceğiniz bir atmosferi bir araya getirir. Her şey doğrudan, güvenilir ve iştah açıcı hissettirmelidir.", pills: ["Taze", "Temiz", "Samimi", "Güvenilir"], caption: "Sultan görünüşte sakin, lezzette nettir.", cards: [["Temiz hazırlık", "Taze malzemeler, düzenli süreçler ve tezgâhtan çok önce başlayan bir kalite anlayışı."], ["Günlük kalite", "25 yıllık deneyim; baharat, sıcaklık ve zamanlamanın doğru olduğu yerde kendini gösterir."], ["Kendine özgü çizgi", "Sıcak, net ve akılda kalıcı – gürültülü değil, özenle ikna edici."]] },
      story: { title: "Hikaye – Sultan Gemüse Kebab Berlin", description: "Sultan Gemüse Kebab’ın hikayesi: 25 yıllık deneyim, aile ve kendi çizgisine sahip bir yer kurma isteği.", eyebrow: "Hikaye", heroTitle: "Deneyimle büyüdü. Gerçek lezzet için kuruldu.", heroLead: "Sultan; yılların emeği, aile geleneği ve kendine özgü bir yer kurma isteğinden doğdu. Bugün sakin görünen her şey, uzun zaman içinde olgunlaştı.", pills: ["25 yıllık deneyim", "Aile işletmesi", "24 saat dinlendirilmiş hamur"], caption: "Kalitenin lezzetle buluştuğu yer – sadece bir slogan değil, günlük bir ölçü.", cards: [["Deneyim", "Rutin; baharat, sıcaklık ve zamanlamanın tesadüfe bırakılmadığı yerde kendini gösterir."], ["Aile", "Sultan, aile işletmesinin yakınlığını, güvenilirliğini ve sorumluluğunu günlük yaşama taşır."], ["İmza", "Bir yer ancak lezzet, duruş ve tanınabilirlik uyumlu olduğunda gerçekten kendine ait olur."]] },
      drinks: { title: "İçecekler – Sultan Gemüse Kebab Berlin", description: "Sultan’da içecekler: Elephant Bay, su ve ayran – soğuk, net tatta ve kebap, lahmacun ile pizzaya uyumlu.", eyebrow: "İçecekler", heroTitle: "Serin, net ve yemekle tam uyumlu.", heroLead: "Baharatlı yemeklerin taze bir eşlikçiye ihtiyacı vardır. Bu yüzden Sultan’daki seçim bilinçli olarak nettir: Elephant Bay, su ve ayran – iyi soğutulmuş ve tam uyumlu.", ctas: ["Menü", "İletişim"], minis: [["Yemekle uyumlu", "Taze, hafif ve yemeklerin lezzetini öne çıkaracak şekilde seçildi."], ["Bilinçli sadelik", "Aşırı kalabalık yerine uyum – tıpkı menüde olduğu gibi."]], blockTitle: "Serinletici içecekler", blockLead: "Kebapla, pizzayla ya da sadece arada: soğuk bir yudum tadı bastırmadan deneyimi tamamlar.", items: [["Elephant Bay", "330 ml"], ["Su", "500 ml"], ["Ayran", "250 ml · Alerjen 7"]], note: "İyi soğutulmuş, net tatta ve baharatlı yemeklerle uyumlu." },
      contact: { title: "İletişim – Sultan Gemüse Kebab Berlin", description: "İletişim, adres, telefon numarası, çalışma saatleri ve Berlin Lichterfelde’de Sultan Gemüse Kebab’a doğrudan yol tarifi.", eyebrow: "İletişim", heroTitle: "Sultan kolay bulunur ve doğrudan ulaşılabilir.", heroLead: "Adres, çalışma saatleri, telefon numarası ve Sultan’a doğrudan yol tarifi tek bakışta. Kısa, net ve dolambaçsız.", cta2: "Yol tarifi aç", minis: [["Adres", "Ostpreußendamm 79<br>12207 Berlin-Lichterfelde"], ["Çalışma saatleri", "Pazartesi – Pazar<br>11:00 – 00:00"], ["E-posta", '<a href="mailto:dnmz.unternehmen@outlook.de">dnmz.unternehmen@outlook.de</a>']], infoTitle: "Doğrudan iletişim", infoParas: ["Sultan Gemüse Kebab<br>Ostpreußendamm 79<br>12207 Berlin", 'Telefon<br><a href="tel:+4917632518597">0176 32518597</a>', 'E-posta<br><a href="mailto:dnmz.unternehmen@outlook.de">dnmz.unternehmen@outlook.de</a>'], mapsOpen: "Google Maps’te aç", mapTitle: "Google Maps’te Sultan" },
      imprint: { title: "Künye – Sultan Gemüse Kebab Berlin", description: "Berlin’deki Sultan Gemüse Kebab için yasal olarak gerekli tüm bilgiler.", eyebrow: "Künye", heroTitle: "Yasal olarak net ve doğrudan ulaşılabilir.", heroLead: "Sultan Gemüse Kebab’a ait yasal olarak gerekli tüm bilgiler tek bakışta.", paras: ["§ 5 DDG uyarınca bilgiler", "Sultan Gemüse Kebab<br>Şahıs işletmesi<br>Ostpreußendamm 79<br>12207 Berlin<br>Almanya", "Temsil eden:<br>Hulusi Dönmez", 'İletişim:<br>E-posta: <a href="mailto:dnmz.unternehmen@outlook.de">dnmz.unternehmen@outlook.de</a><br>Telefon: <a href="tel:+4917632518597">0176 32518597</a>', "§ 27a Alman Katma Değer Vergisi Kanunu uyarınca KDV kimlik numarası:<br>DE2026300369"] },
      privacy: { title: "Gizlilik – Sultan Gemüse Kebab Berlin", description: "Bu web sitesi, gömülü haritalar ve e-posta ile iletişim için Sultan Gemüse Kebab gizlilik bilgileri.", eyebrow: "Gizlilik", heroTitle: "Gizlilik bilgileri anlaşılır şekilde özetlendi.", heroLead: "Bu web sitesinde kişisel verilerin işlenmesine, harita gösterimine ve e-posta ile iletişime dair bilgiler.", paras: ["Kişisel verilerinizin korunması bizim için önemlidir. Bu web sitesi Sultan Gemüse Kebab ve gastronomi teklifimiz hakkında bilgi verir.", "Web sitesi çağrıldığında teknik olarak gerekli veriler işlenebilir. Bunlar özellikle IP adresi, erişim tarihi ve saati, tarayıcı türü, işletim sistemi ve görüntülenen sayfalardır.", "Bu web sitesi GitHub Pages üzerinden yayınlanmaktadır. Sağlayıcı GitHub, Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, USA’dır.", "Ana sayfada ve iletişim sayfasında Google Maps haritaları gömülüdür. Bu haritalar yüklenirken özellikle IP adresiniz olmak üzere veriler Google’a iletilebilir. Sağlayıcı Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, İrlanda’dır.", "Bize e-posta ile ulaşırsanız, ilettiğiniz bilgileri yalnızca talebinizi işlemek amacıyla kullanırız.", 'Veri işlemeden sorumlu kişi:<br>Hulusi Dönmez<br>Sultan Gemüse Kebab<br>Ostpreußendamm 79<br>12207 Berlin<br>E-posta: <a href="mailto:dnmz.unternehmen@outlook.de">dnmz.unternehmen@outlook.de</a><br>Telefon: <a href="tel:+4917632518597">0176 32518597</a>'] },
      menu: { title: "Menü – Sultan Gemüse Kebab Berlin", description: "Sultan menüsü: tavuklu sebzeli kebap, falafel, lahmacun, pizza, salatalar, yan ürünler, tatlılar ve pizza ile ekmek için 24 saat dinlendirilmiş hamur.", eyebrow: "Menü", heroTitle: "İştahı anında açan her şey.", heroLead: "Tavuklu sebzeli kebap, falafel, lahmacun, pizza, salatalar ve tatlılar – net bölünmüş, kolay okunur ve taze dolu lezzetle sunulur.", ctas: ["İçecekler", "Hemen uğrayın"], mini: ["24 saat dinlendirilmiş hamur", "Pizza ve ekmek için Sultan, hamura sonradan tadını veren o gerekli dinlenme süresini tanır."], block1Title: "Döner", block1Subheads: ["Falafel", "Ekstralar"], block1Items: [["Kase", "Tavuklu sebzeli kebap · Alerjenler 1,6,7"], ["Dürüm", "Tavuklu sebzeli kebap · Alerjenler 1,6,7"], ["Kutu", "Tavuklu sebzeli kebap · Alerjenler 1,6,7"], ["Ekmek", "Tavuklu sebzeli kebap · Alerjenler 1,6,7"], ["Kase", "Falafel sebzeli kebap · Alerjenler 1,6,11"], ["Dürüm", "Falafel sebzeli kebap · Alerjenler 1,6,11"], ["Kutu", "Falafel sebzeli kebap · Alerjenler 1,6,11"], ["Ekmek", "Falafel sebzeli kebap · Alerjenler 1,6,11"], ["Ekstra tavuk", "Alerjenler 6,7"], ["Ekstra falafel", "Alerjenler 1,11"], ["Ekstra ekmek", "Alerjen 1"]], sauces: "Soslar: Otlu · Sarımsaklı · Acı Vegan · Sarımsaklı Vegan · Susam Vegan.", block2Title: "Lahmacun", block2Subhead: "Pizza 28 cm", block2Items: [["10 adet", "fırından taze · Alerjen 1"], ["5 adet", "fırından taze · Alerjen 1"], ["3 adet", "fırından taze · Alerjen 1"], ["1 adet", "fırından taze · Alerjen 1"], ["Tonno", "Domates sosu & mozzarella · ton balığı, soğan"], ["Sucuk", "Domates sosu & mozzarella"], ["Salami", "Domates sosu & mozzarella"], ["Prosciutto", "Domates sosu & mozzarella · hindi göğsü"], ["Mista", "Domates sosu & mozzarella · hindi göğsü, salam"], ["Funghi", "Domates sosu & mozzarella · mantar"], ["Vegetaria", "Domates sosu & mozzarella · kabak, patlıcan, biber"], ["Mozzarella", "ekstra mozzarella"], ["Margherita", "mozzarella"]], block3Title: "Salatalar & Yan Ürünler", block3Items: [["Ton balıklı salata", "taze ve hafif"], ["Peynirli salata", "taze ve hafif"], ["Karışık salata", "taze ve hafif"], ["Mercimek çorbası", "ısıtan ve klasik"], ["Patates kızartması", "çıtır servis edilir"], ["Falafel 4 adet", "Alerjenler 1,11"]], block4Title: "Tatlı", block4Items: [["Baklava 3 adet", "Alerjenler 1,3,7,8"], ["Burma 3 adet", "Alerjenler 1,3,7,8"]], dessertNote: "Alerjen bilgileri istek üzerine verilir. İçerikler ve alerjenler hakkında sorularınız için yerinde yardımcı oluyoruz." }
    }
  }
};

function setText(el, value) { if (el) el.textContent = value; }
function setHTML(el, value) { if (el) el.innerHTML = value; }
function updateMeta(name, content) { const el = document.querySelector(`meta[name="${name}"]`); if (el) el.setAttribute("content", content); }
function updateProperty(property, content) { const el = document.querySelector(`meta[property="${property}"]`); if (el) el.setAttribute("content", content); }

function updateCommon(langData) {
  document.documentElement.lang = langData.htmlLang;
  setText(document.querySelector('.skip-link'), langData.skipLink);
  const brand = document.querySelector('.brand'); if (brand) brand.setAttribute('aria-label', langData.brandAria);
  const nav = document.querySelector('.nav-links'); if (nav) nav.setAttribute('aria-label', langData.navAria);
  const tools = document.querySelector('.nav-tools'); if (tools) tools.setAttribute('aria-label', langData.switcherAria);
  setText(document.querySelector('.brand-copy span'), langData.brandTagline);
  const map = [ ['index.html', langData.nav.home], ['unser-laden.html', langData.nav.store], ['geschichte.html', langData.nav.story], ['speisekarte.html', langData.nav.menu], ['getraenke.html', langData.nav.drinks], ['kontakt.html', langData.nav.contact], ['impressum.html', langData.nav.imprint], ['datenschutz.html', langData.nav.privacy] ];
  map.forEach(([href, label]) => { document.querySelectorAll(`.nav-links a[href="${href}"], .footer-links a[href="${href}"]`).forEach(el => setText(el, label)); });
  document.querySelectorAll('footer .footer-inner > span').forEach(el => setText(el, langData.footerCopy));
  setText(document.querySelector('#halal-title'), langData.halalTitle);
  setText(document.querySelector('#halal-text'), langData.halalText);
}

function applyHome(t) {
  setText(document.querySelector('.eyebrow'), t.heroEyebrow); setHTML(document.querySelector('h1'), t.heroTitle); setText(document.querySelector('.lead'), t.heroLead);
  const ctas = document.querySelectorAll('.cta-row a'); if (ctas[0]) setText(ctas[0], t.ctas[0]); if (ctas[1]) setText(ctas[1], t.ctas[1]);
  document.querySelectorAll('.hero-highlights .highlight').forEach((el,i)=>{ if(t.highlights[i]) { setText(el.querySelector('strong'), t.highlights[i][0]); setText(el.querySelector('span'), t.highlights[i][1]); }});
  document.querySelectorAll('.hero-side .mini-panel').forEach((el,i)=>{ if(t.minis[i]) { setText(el.querySelector('strong'), t.minis[i][0]); setText(el.querySelector('span'), t.minis[i][1]); }});
  const heads=document.querySelectorAll('.section-head'); if(heads[0]) { setText(heads[0].querySelector('.kicker'), t.section1[0]); setText(heads[0].querySelector('h2'), t.section1[1]); setText(heads[0].querySelector('p'), t.section1[2]); }
  document.querySelectorAll('.grid-3 .card').forEach((el,i)=>{ if(t.cards[i]) { setText(el.querySelector('h3'), t.cards[i][0]); setText(el.querySelector('p'), t.cards[i][1]); }});
  setText(document.querySelector('.feature-split .visual-card .caption'), t.visualCaption);
  if(heads[1]) { setText(heads[1].querySelector('.kicker'), t.section2[0]); setText(heads[1].querySelector('h2'), t.section2[1]); setText(heads[1].querySelector('p'), t.section2[2]); }
  document.querySelectorAll('.page-link').forEach((el,i)=>{ if(t.pageLinks[i]) { setText(el.querySelector('strong'), t.pageLinks[i][0]); setText(el.querySelector('span'), t.pageLinks[i][1]); }});
  const info=document.querySelector('.info-card'); if(info){ setText(info.querySelector('.kicker'), t.contact[0]); setText(info.querySelector('h2'), t.contact[1]); const ps=info.querySelectorAll('p'); if(ps[0]) setHTML(ps[0], t.contact[2]); if(ps[1]) setHTML(ps[1], t.contact[3]); setText(info.querySelector('.maps-link'), t.contact[4]); }
  const iframe=document.querySelector('iframe'); if(iframe) iframe.title=t.contact[5];
}
function applyStoreLike(t){ setText(document.querySelector('.eyebrow'), t.eyebrow); setText(document.querySelector('h1'), t.heroTitle); setText(document.querySelector('.lead'), t.heroLead); document.querySelectorAll('.pill').forEach((el,i)=>{ if(t.pills[i]) setText(el,t.pills[i]); }); setText(document.querySelector('.visual-card .caption'), t.caption); document.querySelectorAll('.grid-3 .card').forEach((el,i)=>{ if(t.cards[i]) { setText(el.querySelector('h3'), t.cards[i][0]); setText(el.querySelector('p'), t.cards[i][1]); }}); }
function applyDrinks(t){ setText(document.querySelector('.eyebrow'), t.eyebrow); setText(document.querySelector('h1'), t.heroTitle); setText(document.querySelector('.lead'), t.heroLead); const ctas=document.querySelectorAll('.cta-row a'); if(ctas[0]) setText(ctas[0], t.ctas[0]); if(ctas[1]) setText(ctas[1], t.ctas[1]); document.querySelectorAll('.hero-side .mini-panel').forEach((el,i)=>{ if(t.minis[i]) { setText(el.querySelector('strong'), t.minis[i][0]); setText(el.querySelector('span'), t.minis[i][1]); }}); const block=document.querySelector('.menu-block'); if(block){ setText(block.querySelector('h3'), t.blockTitle); setText(block.querySelector('.lead'), t.blockLead); const items=block.querySelectorAll('.menu-item'); items.forEach((item,i)=>{ if(t.items[i]) { setText(item.querySelector('strong'), t.items[i][0]); setText(item.querySelector('small'), t.items[i][1]); }}); setText(block.querySelector('.note'), t.note); } }
function applyContact(t){ setText(document.querySelector('.eyebrow'), t.eyebrow); setText(document.querySelector('h1'), t.heroTitle); setText(document.querySelector('.lead'), t.heroLead); const ctas=document.querySelectorAll('.cta-row a'); if(ctas[1]) setText(ctas[1], t.cta2); document.querySelectorAll('.hero-side .mini-panel').forEach((el,i)=>{ if(t.minis[i]) { setText(el.querySelector('strong'), t.minis[i][0]); setHTML(el.querySelector('span'), t.minis[i][1]); }}); const info=document.querySelector('.info-card'); if(info){ setText(info.querySelector('h3'), t.infoTitle); info.querySelectorAll('p').forEach((p,i)=>{ if(t.infoParas[i]) setHTML(p, t.infoParas[i]); }); setText(info.querySelector('.maps-link'), t.mapsOpen); } const iframe=document.querySelector('iframe'); if(iframe) iframe.title=t.mapTitle; }
function applySimpleHero(t){ setText(document.querySelector('.eyebrow'), t.eyebrow); setText(document.querySelector('h1'), t.heroTitle); setText(document.querySelector('.lead'), t.heroLead); }
function applyLegalParas(paras){ document.querySelectorAll('.legal-copy p').forEach((p,i)=>{ if(paras[i]) setHTML(p, paras[i]); }); }
function applyMenu(t){ setText(document.querySelector('.eyebrow'), t.eyebrow); setText(document.querySelector('h1'), t.heroTitle); setText(document.querySelector('.lead'), t.heroLead); const ctas=document.querySelectorAll('.cta-row a'); if(ctas[0]) setText(ctas[0], t.ctas[0]); if(ctas[1]) setText(ctas[1], t.ctas[1]); const mini=document.querySelector('.mini-panel'); if(mini){ setText(mini.querySelector('strong'), t.mini[0]); setText(mini.querySelector('span'), t.mini[1]); }
  const blocks=document.querySelectorAll('.menu-block');
  if(blocks[0]){
    setText(blocks[0].querySelector('h3'), t.block1Title); const subs=blocks[0].querySelectorAll('.subhead'); if(subs[0]) setText(subs[0], t.block1Subheads[0]); if(subs[1]) setText(subs[1], t.block1Subheads[1]); const items=blocks[0].querySelectorAll('.menu-item'); items.forEach((item,i)=>{ if(t.block1Items[i]) { setText(item.querySelector('strong'), t.block1Items[i][0]); setText(item.querySelector('small'), t.block1Items[i][1]); }}); setText(blocks[0].querySelector('.note'), t.sauces);
  }
  if(blocks[1]){
    setText(blocks[1].querySelector('h3'), t.block2Title); const sub=blocks[1].querySelector('.subhead'); if(sub) setText(sub, t.block2Subhead); const items=blocks[1].querySelectorAll('.menu-item'); items.forEach((item,i)=>{ if(t.block2Items[i]) { setText(item.querySelector('strong'), t.block2Items[i][0]); setText(item.querySelector('small'), t.block2Items[i][1]); }});
  }
  if(blocks[2]){
    setText(blocks[2].querySelector('h3'), t.block3Title); const items=blocks[2].querySelectorAll('.menu-item'); items.forEach((item,i)=>{ if(t.block3Items[i]) { setText(item.querySelector('strong'), t.block3Items[i][0]); setText(item.querySelector('small'), t.block3Items[i][1]); }});
  }
  if(blocks[3]){
    setText(blocks[3].querySelector('h3'), t.block4Title); const items=blocks[3].querySelectorAll('.menu-item'); items.forEach((item,i)=>{ if(t.block4Items[i]) { setText(item.querySelector('strong'), t.block4Items[i][0]); setText(item.querySelector('small'), t.block4Items[i][1]); }}); setText(blocks[3].querySelector('.note'), t.dessertNote);
  }
}

function applyLanguage(lang){
  const current = supportedLangs.includes(lang) ? lang : defaultLang;
  const page = document.body.dataset.page;
  const common = translations[current].common;
  const pageData = translations[current].pages[page];
  updateCommon(common);
  document.title = pageData.title;
  updateMeta('description', pageData.description); updateProperty('og:title', pageData.title); updateProperty('og:description', pageData.description); updateProperty('og:locale', localeMap[current]); updateMeta('twitter:title', pageData.title); updateMeta('twitter:description', pageData.description);
  if(page==='home') applyHome(pageData);
  if(page==='store' || page==='story') applyStoreLike(pageData);
  if(page==='drinks') applyDrinks(pageData);
  if(page==='contact') applyContact(pageData);
  if(page==='imprint'){ applySimpleHero(pageData); applyLegalParas(pageData.paras); }
  if(page==='privacy'){ applySimpleHero(pageData); applyLegalParas(pageData.paras); }
  if(page==='menu') applyMenu(pageData);
  document.querySelectorAll('.lang-btn').forEach(btn => btn.classList.toggle('is-active', btn.dataset.lang===current));
  localStorage.setItem('sultan-lang', current);
}

document.addEventListener('DOMContentLoaded', ()=>{
  const saved = localStorage.getItem('sultan-lang') || defaultLang;
  document.querySelectorAll('.lang-btn').forEach(btn => btn.addEventListener('click', ()=>applyLanguage(btn.dataset.lang)));
  applyLanguage(saved);
});
